apiVersion: v1
kind: ConfigMap
metadata:
  name: schedulerapi-configmap
  labels:
    app: schedulerapi
data:
  COURSE_API_URL: "http://courseapi-service:8001/api/v1"
  STUDENT_API_URL: "http://studentapi-service:8002/api/v1"
  AI_ASSISTANT_API_URL: "http://ai-assistant-api-service:8003/api/v1"
  POSTGRES_USER: "postgres"
  POSTGRES_DB: "schedulerdb"
  DB_HOST: "postgres-service"
  DB_PORT: "5432"
